import { useState } from "react";
import ConsignmentTracker from "./ConsignmentTracker";
import InboundReceiving from "./InboundReceiving";
import ExpiryManagement from "./ExpiryManagement";
import WardDistribution from "./WardDistribution";
import RecallManagement from "./RecallManagement";

const USERS=[{username:"sarak",password:"S@ra2020"},{username:"admin",password:"Admin@123"}];
const SAMPLE_EMAILS=[{label:"🇦🇺 AU Supplier",text:`From: brett@southerncross.com.au\nASN Reference: ASN-20240601\nPO Number: PO-88123\nShip Date: 2024-06-03\nETA: 2024-06-05\nCarrier: StarTrack\nTracking: TRK99887766\nItems:\n- SKU: ELE-4521-A | Industrial Control Module | Qty: 50 EA | Batch: BT-11234\n- SKU: MEC-8834-B | Bearing Assembly | Qty: 20 SET | Batch: BT-11235\nCartons: 12 | Weight: 240 kg`},{label:"🇨🇳 China Supplier",text:`发件人: export@china.cn\nASN No: ASN-CN-88712\nPO: PO-77654\nShip Date: 2024-06-04\nETA: 2024-06-18\nCarrier: Maersk Line\nTracking: MRKU1234567\nItems: LED Driver 100W | Qty: 200 EA | Batch: BT-55001`}];
const S={page:{minHeight:"100vh",background:"#0f1117",color:"#e8eaf0",fontFamily:"system-ui,sans-serif"},header:{background:"#1a1d27",borderBottom:"1px solid #2a2d3a",padding:"14px 24px",display:"flex",alignItems:"center",gap:12},input:{width:"100%",padding:"10px 12px",background:"#0f1117",border:"1px solid #2a2d3a",borderRadius:8,color:"#e8eaf0",fontSize:14,outline:"none",boxSizing:"border-box"},btn:(c="#4f8ef7")=>({padding:"11px 20px",background:c,border:"none",borderRadius:8,color:"#fff",fontWeight:600,fontSize:14,cursor:"pointer",width:"100%"}),card:{background:"#1a1d27",border:"1px solid #2a2d3a",borderRadius:10,padding:20},metric:{background:"#0f1117",borderRadius:8,padding:"14px 16px"},grid:(n)=>({display:"grid",gridTemplateColumns:`repeat(${n},1fr)`,gap:12})};

function Login({onLogin}){const[u,setU]=useState("");const[p,setP]=useState("");const[err,setErr]=useState("");const submit=()=>{const m=USERS.find(x=>x.username===u&&x.password===p);if(m)onLogin(u);else setErr("Invalid credentials.");};return(<div style={{...S.page,display:"flex",alignItems:"center",justifyContent:"center"}}><div style={{...S.card,width:360}}><div style={{textAlign:"center",marginBottom:24}}><div style={{fontSize:40,marginBottom:10}}>🏥</div><h2 style={{fontSize:20,fontWeight:600,margin:0}}>Hospital Supply Chain</h2><p style={{fontSize:13,color:"#8b8fa8",margin:"6px 0 0"}}>Logistics & Consignment Management</p></div>{err&&<p style={{color:"#ef4444",fontSize:12,marginBottom:10}}>{err}</p>}<div style={{marginBottom:12}}><label style={{fontSize:12,color:"#8b8fa8",display:"block",marginBottom:6}}>Username</label><input style={S.input} value={u} onChange={e=>setU(e.target.value)} onKeyDown={e=>e.key==="Enter"&&submit()}/></div><div style={{marginBottom:16}}><label style={{fontSize:12,color:"#8b8fa8",display:"block",marginBottom:6}}>Password</label><input type="password" style={S.input} value={p} onChange={e=>setP(e.target.value)} onKeyDown={e=>e.key==="Enter"&&submit()}/></div><button style={S.btn()} onClick={submit}>Sign in</button></div></div>);}

function ASNParser(){const[email,setEmail]=useState("");const[asn1,setAsn1]=useState("");const[asn2,setAsn2]=useState("");const[loading,setLoading]=useState(false);const[error,setError]=useState("");const parse=async()=>{if(!email.trim())return;setLoading(true);setError("");setAsn1("");setAsn2("");try{const r=await fetch("/api/parse-email",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})});const d=await r.json();if(d.error){setError(d.error);return;}setAsn1(d.asn1||d.result||"");setAsn2(d.asn2||"");}catch{setError("Error connecting to Groq API. Check GROQ_KEY in Vercel.");}setLoading(false);};return(<div style={S.page}><div style={S.header}><span style={{fontSize:24}}>📧</span><div><div style={{fontSize:16,fontWeight:600}}>ASN Parser</div><div style={{fontSize:11,color:"#8b8fa8"}}>Groq AI · LLaMA 3.3 70B</div></div></div><div style={{padding:"24px",maxWidth:900,margin:"0 auto"}}><div style={S.card}><div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:14}}>{SAMPLE_EMAILS.map((s,i)=><button key={i} style={{padding:"6px 14px",borderRadius:8,fontSize:12,cursor:"pointer",border:"1px solid #2a2d3a",background:"transparent",color:"#8b8fa8"}} onClick={()=>setEmail(s.text)}>{s.label}</button>)}</div><textarea style={{...S.input,minHeight:180,resize:"vertical",fontFamily:"monospace",marginBottom:12}} value={email} onChange={e=>setEmail(e.target.value)} placeholder="Paste supplier email here…"/><button style={{...S.btn(),width:"auto",padding:"10px 24px"}} onClick={parse} disabled={loading}>{loading?"⏳ Parsing…":"✦ Generate ASN 1 & ASN 2"}</button>{error&&<p style={{color:"#ef4444",fontSize:12,marginTop:10}}>{error}</p>}</div>{(asn1||asn2)&&<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14,marginTop:14}}>{[["ASN 1",asn1],["ASN 2",asn2]].map(([l,v])=>v&&<div key={l} style={S.card}><div style={{fontWeight:600,fontSize:13,marginBottom:10,color:"#4f8ef7"}}>{l}</div><pre style={{fontSize:11,color:"#8b8fa8",whiteSpace:"pre-wrap",margin:0,fontFamily:"monospace",lineHeight:1.7}}>{v}</pre></div>)}</div>}</div></div>);}

function Dashboard({onNav}){const MODULES=[{id:"asn",icon:"📧",title:"ASN Parser",desc:"Groq AI email → ASN 1 & ASN 2",color:"#4f8ef7",kpi:"3 pending"},{id:"inbound",icon:"📦",title:"Inbound Receiving",desc:"GRN, 3-way match, cold chain",color:"#22c55e",kpi:"2 ASNs due"},{id:"consignment",icon:"🔬",title:"Consignment Manager",desc:"Implant tracking & reconciliation",color:"#a855f7",kpi:"386 lines"},{id:"expiry",icon:"📅",title:"Expiry Management",desc:"FEFO · 90/60/30d alerts",color:"#f59e0b",kpi:"4 expiring"},{id:"ward",icon:"🚚",title:"Ward Distribution",desc:"Requisitions · Delivery · Returns",color:"#14b8a6",kpi:"99.2% fill"},{id:"recall",icon:"🚨",title:"Recall Management",desc:"TGA recall · Batch traceability",color:"#ef4444",kpi:"1 ACTIVE"}];
return(<div style={S.page}><div style={S.header}><span style={{fontSize:26}}>🏥</span><div style={{flex:1}}><div style={{fontSize:17,fontWeight:600}}>Hospital Supply Chain</div><div style={{fontSize:11,color:"#8b8fa8"}}>Logistics & Consignment Management</div></div></div><div style={{padding:"24px",maxWidth:1100,margin:"0 auto"}}>
<div style={{background:"#450a0a",border:"1px solid #ef4444",borderRadius:10,padding:"12px 18px",marginBottom:20,display:"flex",alignItems:"center",gap:12}}><span style={{fontSize:18}}>🚨</span><div><span style={{fontWeight:600,color:"#ef4444",fontSize:13}}>Active recall — Stryker Triathlon Knee System (BT-20240501)</span><span style={{fontSize:12,color:"#fca5a5",marginLeft:12}}>Class II | TGA-RC-2024-0412</span></div><button style={{marginLeft:"auto",padding:"5px 14px",background:"#ef4444",border:"none",borderRadius:6,color:"#fff",fontSize:12,fontWeight:600,cursor:"pointer"}} onClick={()=>onNav("recall")}>Respond →</button></div>
<div style={{...S.grid(6),marginBottom:24}}>{[["ASNs pending","3","#f59e0b"],["GRNs today","7","#22c55e"],["Consignment lines","386","#4f8ef7"],["Expiring ≤30d","4","#ef4444"],["Ward fill rate","99.2%","#22c55e"],["Active recalls","1","#ef4444"]].map(([l,v,c])=><div key={l} style={S.metric}><div style={{fontSize:11,color:"#8b8fa8",marginBottom:4}}>{l}</div><div style={{fontSize:20,fontWeight:700,color:c}}>{v}</div></div>)}</div>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(300px,1fr))",gap:14}}>{MODULES.map(m=><div key={m.id} style={{...S.card,cursor:"pointer",borderLeft:`3px solid ${m.color}`}} onClick={()=>onNav(m.id)}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:10}}><div style={{display:"flex",alignItems:"center",gap:10}}><span style={{fontSize:24}}>{m.icon}</span><div><div style={{fontSize:14,fontWeight:600}}>{m.title}</div><span style={{fontSize:11,padding:"2px 8px",borderRadius:4,background:`${m.color}22`,color:m.color,fontWeight:600}}>{m.kpi}</span></div></div><span style={{fontSize:18,color:"#2a2d3a"}}>→</span></div><div style={{fontSize:12,color:"#8b8fa8",lineHeight:1.6}}>{m.desc}</div></div>)}</div>
</div></div>);}

export default function App(){const[user,setUser]=useState(null);const[screen,setScreen]=useState("dashboard");if(!user)return<Login onLogin={setUser}/>;const SCREENS={dashboard:<Dashboard onNav={setScreen}/>,asn:<ASNParser/>,inbound:<InboundReceiving/>,consignment:<ConsignmentTracker/>,expiry:<ExpiryManagement/>,ward:<WardDistribution/>,recall:<RecallManagement/>};return(<div><div style={{background:"#0a0c12",padding:"8px 20px",borderBottom:"1px solid #2a2d3a",display:"flex",alignItems:"center",gap:12}}>{screen!=="dashboard"&&<button style={{padding:"4px 12px",borderRadius:6,fontSize:12,cursor:"pointer",border:"1px solid #2a2d3a",background:"transparent",color:"#8b8fa8"}} onClick={()=>setScreen("dashboard")}>← Dashboard</button>}<span style={{marginLeft:"auto",fontSize:12,color:"#8b8fa8"}}>Logged in as {user}</span><button style={{padding:"4px 12px",borderRadius:6,fontSize:12,cursor:"pointer",border:"1px solid #2a2d3a",background:"transparent",color:"#8b8fa8"}} onClick={()=>setUser(null)}>Sign out</button></div>{SCREENS[screen]}</div>);}
