import { useState } from "react";
const SUPPLIERS = ["Stryker","Zimmer Biomet","Medtronic","Johnson & Johnson","Smith+Nephew","Abbott","Boston Scientific"];
const CATEGORIES = ["Orthopaedic Implants","Cardiac Devices","Vascular Stents","Ophthalmic","Neurosurgery","General Surgery"];
const LOCATIONS = ["Theatre 1 Store","Theatre 2 Store","Cath Lab","ICU Store","Main Warehouse","Sterile Supply"];
const SAMPLE = [
  {id:"CON-001",supplier:"Stryker",category:"Orthopaedic Implants",product:"Triathlon Knee System",sku:"STR-TRI-001",batch:"BT-20240501",expiry:"2026-06-01",qty:4,location:"Theatre 1 Store",status:"active"},
  {id:"CON-002",supplier:"Medtronic",category:"Cardiac Devices",product:"Micra AV Pacemaker",sku:"MDT-MIC-002",batch:"BT-20240312",expiry:"2025-12-01",qty:2,location:"Cath Lab",status:"active"},
  {id:"CON-003",supplier:"Zimmer Biomet",category:"Orthopaedic Implants",product:"Persona Hip System",sku:"ZB-PER-003",batch:"BT-20231101",expiry:"2024-08-01",qty:6,location:"Theatre 2 Store",status:"expiring"},
  {id:"CON-004",supplier:"Abbott",category:"Vascular Stents",product:"Xience Sierra Stent",sku:"ABT-XIE-004",batch:"BT-20240201",expiry:"2025-09-01",qty:3,location:"Cath Lab",status:"active"},
];
const USAGE = [
  {id:"USE-001",consignmentId:"CON-001",product:"Triathlon Knee System",patient:"PT-88421",surgeon:"Dr. Chen",theatre:"Theatre 1",date:"2024-06-10",qty:1,invoiced:true},
  {id:"USE-002",consignmentId:"CON-002",product:"Micra AV Pacemaker",patient:"PT-77312",surgeon:"Dr. Patel",theatre:"Cath Lab",date:"2024-06-08",qty:1,invoiced:false},
];
const S={page:{minHeight:"100vh",background:"#0f1117",color:"#e8eaf0",fontFamily:"system-ui,sans-serif"},header:{background:"#1a1d27",borderBottom:"1px solid #2a2d3a",padding:"14px 24px",display:"flex",alignItems:"center",gap:12},nav:{display:"flex",borderBottom:"1px solid #2a2d3a",background:"#1a1d27",padding:"0 24px"},tab:(a)=>({padding:"11px 18px",fontSize:13,cursor:"pointer",border:"none",background:"transparent",color:a?"#4f8ef7":"#8b8fa8",borderBottom:a?"2px solid #4f8ef7":"2px solid transparent",fontWeight:a?500:400}),body:{padding:"20px 24px",maxWidth:1100,margin:"0 auto"},card:{background:"#1a1d27",border:"1px solid #2a2d3a",borderRadius:10,padding:18,marginBottom:14},label:{fontSize:11,fontWeight:600,letterSpacing:"0.07em",color:"#8b8fa8",textTransform:"uppercase",display:"block",marginBottom:6},input:{width:"100%",padding:"9px 12px",background:"#0f1117",border:"1px solid #2a2d3a",borderRadius:8,color:"#e8eaf0",fontSize:13,outline:"none",boxSizing:"border-box"},select:{width:"100%",padding:"9px 12px",background:"#0f1117",border:"1px solid #2a2d3a",borderRadius:8,color:"#e8eaf0",fontSize:13,outline:"none",boxSizing:"border-box"},btn:(c="#4f8ef7")=>({padding:"9px 18px",background:c,border:"none",borderRadius:8,color:"#fff",fontWeight:600,fontSize:13,cursor:"pointer"}),btnSm:(c="#4f8ef7")=>({padding:"5px 12px",background:"transparent",border:`1px solid ${c}`,borderRadius:6,color:c,fontSize:11,cursor:"pointer"}),badge:(c)=>{const m={active:["#22c55e","#14532d"],expiring:["#f59e0b","#451a03"],recalled:["#ef4444","#450a0a"]};const[t,b]=m[c]||["#8b8fa8","#1a1d27"];return{padding:"3px 8px",borderRadius:6,fontSize:11,fontWeight:600,color:t,background:b}},grid:(n)=>({display:"grid",gridTemplateColumns:`repeat(${n},1fr)`,gap:12,marginBottom:16}),metric:{background:"#0f1117",borderRadius:8,padding:"12px 14px"},th:{padding:"10px 14px",fontSize:11,fontWeight:600,color:"#8b8fa8",textAlign:"left",borderBottom:"1px solid #2a2d3a",textTransform:"uppercase"},td:{padding:"11px 14px",fontSize:13,borderBottom:"1px solid #1a1d27",verticalAlign:"middle"}};
export default function ConsignmentTracker(){
  const[tab,setTab]=useState("register");
  const[items,setItems]=useState(SAMPLE);
  const[usage,setUsage]=useState(USAGE);
  const[showForm,setShowForm]=useState(false);
  const[showUsageForm,setShowUsageForm]=useState(false);
  const[filter,setFilter]=useState("all");
  const[form,setForm]=useState({supplier:"",category:"",product:"",sku:"",batch:"",expiry:"",qty:"",location:""});
  const[usageForm,setUsageForm]=useState({consignmentId:"",patient:"",surgeon:"",theatre:"",qty:1});
  const filtered=filter==="all"?items:items.filter(i=>i.status===filter);
  const addItem=()=>{setItems([...items,{...form,id:`CON-${String(items.length+1).padStart(3,"0")}`,status:"active",qty:parseInt(form.qty)||0}]);setForm({supplier:"",category:"",product:"",sku:"",batch:"",expiry:"",qty:"",location:""});setShowForm(false);};
  const recordUsage=()=>{const item=items.find(i=>i.id===usageForm.consignmentId);if(!item)return;setUsage([...usage,{...usageForm,id:`USE-${String(usage.length+1).padStart(3,"0")}`,product:item.product,date:new Date().toISOString().split("T")[0],invoiced:false}]);setItems(items.map(i=>i.id===usageForm.consignmentId?{...i,qty:i.qty-parseInt(usageForm.qty)}:i));setUsageForm({consignmentId:"",patient:"",surgeon:"",theatre:"",qty:1});setShowUsageForm(false);};
  const markInvoiced=(id)=>setUsage(usage.map(u=>u.id===id?{...u,invoiced:true}:u));
  const pendingInvoice=usage.filter(u=>!u.invoiced).length;
  return(<div style={S.page}><div style={S.header}><span style={{fontSize:24}}>🔬</span><div><div style={{fontSize:16,fontWeight:600}}>Consignment Manager</div><div style={{fontSize:11,color:"#8b8fa8"}}>Hospital Medical Device Consignment</div></div></div><div style={S.nav}>{[["register","Register"],["usage","Usage Capture"],["reconcile","Reconciliation"]].map(([id,l])=><button key={id} style={S.tab(tab===id)} onClick={()=>setTab(id)}>{l}</button>)}</div><div style={S.body}><div style={S.grid(4)}>{[["Total items",items.length,"#4f8ef7"],["Expiring soon",items.filter(i=>i.status==="expiring").length,"#f59e0b"],["Usage records",usage.length,"#22c55e"],["Pending invoice",pendingInvoice,"#ef4444"]].map(([l,v,c])=><div key={l} style={S.metric}><div style={{fontSize:11,color:"#8b8fa8",marginBottom:4}}>{l}</div><div style={{fontSize:22,fontWeight:600,color:c}}>{v}</div></div>)}</div>
  {tab==="register"&&<div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14}}><div style={{display:"flex",gap:6}}>{["all","active","expiring"].map(f=><button key={f} style={{padding:"5px 12px",borderRadius:6,fontSize:12,cursor:"pointer",border:"1px solid #2a2d3a",background:filter===f?"#1e3a6e":"transparent",color:filter===f?"#4f8ef7":"#8b8fa8"}} onClick={()=>setFilter(f)}>{f.charAt(0).toUpperCase()+f.slice(1)}</button>)}</div><button style={S.btn()} onClick={()=>setShowForm(!showForm)}>+ Add consignment</button></div>{showForm&&<div style={S.card}><div style={{fontSize:14,fontWeight:600,marginBottom:14}}>New consignment item</div><div style={S.grid(3)}>{[["Supplier","supplier",SUPPLIERS],["Category","category",CATEGORIES],["Location","location",LOCATIONS]].map(([l,k,opts])=><div key={k}><label style={S.label}>{l}</label><select style={S.select} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}><option value="">Select…</option>{opts.map(o=><option key={o}>{o}</option>)}</select></div>)}{[["Product name","product"],["SKU","sku"],["Batch/Lot","batch"],["Expiry date","expiry"],["Quantity","qty"]].map(([l,k])=><div key={k}><label style={S.label}>{l}</label><input style={S.input} type={k==="expiry"?"date":k==="qty"?"number":"text"} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></div>)}</div><div style={{display:"flex",gap:8}}><button style={S.btn()} onClick={addItem}>Save</button><button style={S.btn("#333")} onClick={()=>setShowForm(false)}>Cancel</button></div></div>}<div style={{...S.card,padding:0,overflow:"hidden"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr>{["ID","Supplier","Product","Batch","Expiry","Qty","Location","Status","Action"].map(h=><th key={h} style={S.th}>{h}</th>)}</tr></thead><tbody>{filtered.map(item=><tr key={item.id}><td style={{...S.td,fontFamily:"monospace",fontSize:11,color:"#8b8fa8"}}>{item.id}</td><td style={S.td}>{item.supplier}</td><td style={S.td}><div style={{fontSize:13,fontWeight:500}}>{item.product}</div><div style={{fontSize:11,color:"#8b8fa8"}}>{item.sku}</div></td><td style={{...S.td,fontFamily:"monospace",fontSize:11}}>{item.batch}</td><td style={S.td}>{item.expiry}</td><td style={{...S.td,fontWeight:600,color:item.qty<=1?"#ef4444":"#e8eaf0"}}>{item.qty}</td><td style={{...S.td,fontSize:12,color:"#8b8fa8"}}>{item.location}</td><td style={S.td}><span style={S.badge(item.status)}>{item.status}</span></td><td style={S.td}><button style={S.btnSm("#22c55e")} onClick={()=>{setUsageForm({...usageForm,consignmentId:item.id});setShowUsageForm(true);setTab("usage");}}>Record use</button></td></tr>)}</tbody></table></div></div>}
  {tab==="usage"&&<div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14}}><div style={{fontSize:14,fontWeight:500}}>Usage records</div><button style={S.btn()} onClick={()=>setShowUsageForm(!showUsageForm)}>+ Record usage</button></div>{showUsageForm&&<div style={S.card}><div style={{fontSize:14,fontWeight:600,marginBottom:14}}>Capture usage at point of care</div><div style={S.grid(3)}><div><label style={S.label}>Consignment item</label><select style={S.select} value={usageForm.consignmentId} onChange={e=>setUsageForm({...usageForm,consignmentId:e.target.value})}><option value="">Select…</option>{items.map(i=><option key={i.id} value={i.id}>{i.product} ({i.id})</option>)}</select></div>{[["Patient ID","patient"],["Surgeon","surgeon"],["Theatre","theatre"]].map(([l,k])=><div key={k}><label style={S.label}>{l}</label><input style={S.input} value={usageForm[k]||""} onChange={e=>setUsageForm({...usageForm,[k]:e.target.value})}/></div>)}<div><label style={S.label}>Qty used</label><input style={S.input} type="number" min={1} value={usageForm.qty} onChange={e=>setUsageForm({...usageForm,qty:parseInt(e.target.value)||1})}/></div></div><div style={{display:"flex",gap:8}}><button style={S.btn("#22c55e")} onClick={recordUsage}>Confirm usage</button><button style={S.btn("#333")} onClick={()=>setShowUsageForm(false)}>Cancel</button></div></div>}<div style={{...S.card,padding:0,overflow:"hidden"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr>{["ID","Product","Patient","Surgeon","Theatre","Date","Qty","Status","Action"].map(h=><th key={h} style={S.th}>{h}</th>)}</tr></thead><tbody>{usage.map(u=><tr key={u.id}><td style={{...S.td,fontFamily:"monospace",fontSize:11,color:"#8b8fa8"}}>{u.id}</td><td style={S.td}>{u.product}</td><td style={{...S.td,fontFamily:"monospace",fontSize:12}}>{u.patient}</td><td style={S.td}>{u.surgeon}</td><td style={S.td}>{u.theatre}</td><td style={S.td}>{u.date}</td><td style={{...S.td,fontWeight:600}}>{u.qty}</td><td style={S.td}><span style={S.badge(u.invoiced?"active":"expiring")}>{u.invoiced?"Invoiced":"Pending"}</span></td><td style={S.td}>{!u.invoiced&&<button style={S.btnSm()} onClick={()=>markInvoiced(u.id)}>Mark invoiced</button>}</td></tr>)}</tbody></table></div></div>}
  {tab==="reconcile"&&<div style={S.card}><div style={{fontSize:14,fontWeight:600,marginBottom:14}}>Monthly reconciliation</div><div style={S.grid(3)}>{SUPPLIERS.slice(0,3).map(sup=>{const si=items.filter(i=>i.supplier===sup);const su=usage.filter(u=>si.some(i=>i.id===u.consignmentId));const p=su.filter(u=>!u.invoiced).length;return<div key={sup} style={{background:"#0f1117",borderRadius:8,padding:14}}><div style={{fontSize:13,fontWeight:600,marginBottom:8}}>{sup}</div><div style={{fontSize:12,color:"#8b8fa8"}}>On hand: <span style={{color:"#e8eaf0",fontWeight:500}}>{si.reduce((a,i)=>a+i.qty,0)}</span></div><div style={{fontSize:12,color:"#8b8fa8",marginTop:4}}>Used: <span style={{color:"#22c55e",fontWeight:500}}>{su.length}</span></div><div style={{fontSize:12,color:"#8b8fa8",marginTop:4}}>Pending invoice: <span style={{color:p?"#ef4444":"#22c55e",fontWeight:500}}>{p}</span></div><button style={{...S.btnSm(),marginTop:10,width:"100%",textAlign:"center"}} onClick={()=>alert(`Reconciliation sent to ${sup}`)}>Send reconciliation</button></div>})}</div></div>}
  </div></div>);}
