import { useState } from "react";
const today=new Date();
const addDays=(n)=>{const d=new Date(today);d.setDate(d.getDate()+n);return d.toISOString().split("T")[0];};
const daysUntil=(s)=>Math.ceil((new Date(s)-today)/86400000);
const SAMPLE=[{id:"INV-001",sku:"STR-TRI-001",desc:"Triathlon Knee System",supplier:"Stryker",location:"Theatre 1",batch:"BT-20231101",expiry:addDays(18),qty:3,value:4200},{id:"INV-002",sku:"PFZ-VAX-001",desc:"Comirnaty COVID Vaccine",supplier:"Pfizer",location:"Pharmacy Fridge",batch:"BT-20240310",expiry:addDays(45),qty:40,value:1800},{id:"INV-003",sku:"MDT-MIC-002",desc:"Micra AV Pacemaker",supplier:"Medtronic",location:"Cath Lab",batch:"BT-20220901",expiry:addDays(8),qty:1,value:9500},{id:"INV-004",sku:"ABT-XIE-004",desc:"Xience Sierra Stent",supplier:"Abbott",location:"Cath Lab",batch:"BT-20240201",expiry:addDays(72),qty:4,value:2800},{id:"INV-005",sku:"ZB-PER-003",desc:"Persona Hip System",supplier:"Zimmer Biomet",location:"Theatre 2",batch:"BT-20231001",expiry:addDays(28),qty:2,value:5600},{id:"INV-006",sku:"MED-AMX-001",desc:"Amoxicillin 500mg x100",supplier:"Generic Pharma",location:"Pharmacy",batch:"BT-20240201",expiry:addDays(-5),qty:12,value:180}];
const band=(d)=>{if(d<0)return{label:"EXPIRED",color:"#ef4444",bg:"#450a0a"};if(d<=30)return{label:"≤30 days",color:"#ef4444",bg:"#450a0a"};if(d<=60)return{label:"≤60 days",color:"#f59e0b",bg:"#451a03"};if(d<=90)return{label:"≤90 days",color:"#eab308",bg:"#422006"};return{label:"OK",color:"#22c55e",bg:"#14532d"};};
const S={page:{minHeight:"100vh",background:"#0f1117",color:"#e8eaf0",fontFamily:"system-ui,sans-serif"},header:{background:"#1a1d27",borderBottom:"1px solid #2a2d3a",padding:"14px 24px",display:"flex",alignItems:"center",gap:12},nav:{display:"flex",borderBottom:"1px solid #2a2d3a",background:"#1a1d27",padding:"0 24px"},tab:(a)=>({padding:"11px 18px",fontSize:13,cursor:"pointer",border:"none",background:"transparent",color:a?"#4f8ef7":"#8b8fa8",borderBottom:a?"2px solid #4f8ef7":"2px solid transparent",fontWeight:a?500:400}),body:{padding:"20px 24px",maxWidth:1100,margin:"0 auto"},card:{background:"#1a1d27",border:"1px solid #2a2d3a",borderRadius:10,padding:18,marginBottom:14},select:{width:"130px",padding:"4px 8px",background:"#0f1117",border:"1px solid #2a2d3a",borderRadius:8,color:"#e8eaf0",fontSize:11,outline:"none"},grid:(n)=>({display:"grid",gridTemplateColumns:`repeat(${n},1fr)`,gap:12,marginBottom:16}),metric:{background:"#0f1117",borderRadius:8,padding:"12px 14px"},th:{padding:"10px 14px",fontSize:11,fontWeight:600,color:"#8b8fa8",textAlign:"left",borderBottom:"1px solid #2a2d3a",textTransform:"uppercase"},td:{padding:"11px 14px",fontSize:13,borderBottom:"1px solid #1a1d27",verticalAlign:"middle"}};
export default function ExpiryManagement(){
const[tab,setTab]=useState("alerts");
const[items,setItems]=useState(SAMPLE.map(i=>({...i,action:"none",days:daysUntil(i.expiry)})));
const[filter,setFilter]=useState("all");
const sorted=[...items].sort((a,b)=>a.days-b.days);
const filtered=filter==="all"?sorted:sorted.filter(i=>{if(filter==="expired")return i.days<0;if(filter==="30")return i.days>=0&&i.days<=30;if(filter==="60")return i.days>30&&i.days<=60;return true;});
const setAction=(id,action)=>setItems(items.map(i=>i.id===id?{...i,action}:i));
const expired=items.filter(i=>i.days<0);const d30=items.filter(i=>i.days>=0&&i.days<=30);
return(<div style={S.page}><div style={S.header}><span style={{fontSize:24}}>📅</span><div><div style={{fontSize:16,fontWeight:600}}>Expiry Management</div><div style={{fontSize:11,color:"#8b8fa8"}}>FEFO Compliance & Alerts</div></div></div><div style={S.nav}>{[["alerts","Expiry Alerts"],["fefo","FEFO Picking"],["actions","Action Log"]].map(([id,l])=><button key={id} style={S.tab(tab===id)} onClick={()=>setTab(id)}>{l}</button>)}</div><div style={S.body}><div style={S.grid(4)}>{[["Expired",expired.length,"#ef4444"],["Expiring ≤30d",d30.length,"#ef4444"],["At-risk value",`$${[...expired,...d30].reduce((a,i)=>a+i.value,0).toLocaleString()}`,"#f59e0b"],["Total items",items.length,"#8b8fa8"]].map(([l,v,c])=><div key={l} style={S.metric}><div style={{fontSize:11,color:"#8b8fa8",marginBottom:4}}>{l}</div><div style={{fontSize:22,fontWeight:600,color:c}}>{v}</div></div>)}</div>
{tab==="alerts"&&<div><div style={{display:"flex",gap:6,marginBottom:14,flexWrap:"wrap"}}>{[["all","All"],["expired","Expired"],["30","≤30d"],["60","≤60d"]].map(([f,l])=><button key={f} style={{padding:"5px 12px",borderRadius:6,fontSize:12,cursor:"pointer",border:"1px solid #2a2d3a",background:filter===f?"#1e3a6e":"transparent",color:filter===f?"#4f8ef7":"#8b8fa8"}} onClick={()=>setFilter(f)}>{l}</button>)}</div><div style={{...S.card,padding:0,overflow:"hidden"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr>{["Alert","Product","Supplier","Batch","Expiry","Days","Qty","Value","Action"].map(h=><th key={h} style={S.th}>{h}</th>)}</tr></thead><tbody>{filtered.map(item=>{const b=band(item.days);return(<tr key={item.id} style={{background:item.days<0?"#1a0a0a":""}}><td style={S.td}><span style={{padding:"3px 8px",borderRadius:6,fontSize:11,fontWeight:600,color:b.color,background:b.bg}}>{b.label}</span></td><td style={S.td}><div style={{fontSize:13,fontWeight:500}}>{item.desc}</div><div style={{fontSize:11,color:"#8b8fa8",fontFamily:"monospace"}}>{item.sku}</div></td><td style={{...S.td,fontSize:12}}>{item.supplier}</td><td style={{...S.td,fontFamily:"monospace",fontSize:11}}>{item.batch}</td><td style={S.td}>{item.expiry}</td><td style={{...S.td,fontWeight:700,color:b.color}}>{item.days<0?`${Math.abs(item.days)}d ago`:`${item.days}d`}</td><td style={{...S.td,fontWeight:600}}>{item.qty}</td><td style={{...S.td,color:"#f59e0b"}}>${item.value.toLocaleString()}</td><td style={S.td}><select style={S.select} value={item.action} onChange={e=>setAction(item.id,e.target.value)}><option value="none">Action…</option><option value="return">Return to supplier</option><option value="transfer">Transfer</option><option value="quarantine">Quarantine</option><option value="dispose">Dispose</option><option value="use">Prioritise use</option></select></td></tr>);})}</tbody></table></div></div>}
{tab==="fefo"&&<div style={S.card}><div style={{fontSize:14,fontWeight:600,marginBottom:4}}>FEFO pick list — earliest expiry first</div><div style={{fontSize:12,color:"#8b8fa8",marginBottom:14}}>Always pick the item closest to expiry first.</div>{sorted.filter(i=>i.days>=0).map(item=><div key={item.id} style={{display:"flex",alignItems:"center",gap:14,padding:"10px 0",borderBottom:"1px solid #2a2d3a"}}><div style={{width:6,height:40,borderRadius:3,background:band(item.days).color,flexShrink:0}}/><div style={{flex:1}}><div style={{fontSize:13,fontWeight:500}}>{item.desc}</div><div style={{fontSize:11,color:"#8b8fa8"}}>Batch: {item.batch} | {item.location} | Qty: {item.qty}</div></div><div style={{textAlign:"right"}}><div style={{fontSize:16,fontWeight:700,color:band(item.days).color}}>{item.days}d</div><div style={{fontSize:11,color:"#8b8fa8"}}>{item.expiry}</div></div></div>)}</div>}
{tab==="actions"&&<div style={S.card}><div style={{fontSize:14,fontWeight:600,marginBottom:14}}>Items with actions assigned</div>{items.filter(i=>i.action!=="none").length===0?<div style={{textAlign:"center",color:"#8b8fa8",padding:30}}>No actions assigned yet.</div>:items.filter(i=>i.action!=="none").map(item=><div key={item.id} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"10px 0",borderBottom:"1px solid #2a2d3a"}}><div><div style={{fontSize:13,fontWeight:500}}>{item.desc}</div><div style={{fontSize:11,color:"#8b8fa8"}}>Batch: {item.batch} | Exp: {item.expiry} | ${item.value.toLocaleString()}</div></div><div style={{display:"flex",alignItems:"center",gap:10}}><span style={{padding:"4px 10px",borderRadius:6,fontSize:12,fontWeight:600,background:"#1e3a6e",color:"#4f8ef7"}}>{item.action}</span><button style={{padding:"5px 12px",background:"transparent",border:"1px solid #22c55e",borderRadius:6,color:"#22c55e",fontSize:11,cursor:"pointer"}} onClick={()=>alert(`Notification sent for ${item.desc}`)}>Send notification</button></div></div>)}</div>}
</div></div>);}
